In [1]:
import pandas as pd

In [3]:
well_code_list = [7405, 7078, 5599, 5351, 7289]

df_list = [pd.read_csv(f'../datasets/well_data/well_{well_code}_data.csv') for well_code in well_code_list]

df = pd.concat(df_list)

In [5]:
df

,DATEPRD,AVG_DOWNHOLE_PRESSURE,AVG_DOWNHOLE_TEMPERATURE,AVG_DP_TUBING,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,AVG_WHP_P,AVG_WHT_P,DP_CHOKE_SIZE,BORE_OIL_VOL,BORE_GAS_VOL,BORE_WAT_VOL
0,2014-04-07,0.00000,0.00000,0.00000,0.0,0.000000,0.00000,0.00000,0.00000,0.0,0.0,0.0
1,2014-04-08,0.00000,0.00000,0.00000,0.0,1.003059,0.00000,0.00000,0.00000,0.0,0.0,0.0
2,2014-04-09,0.00000,0.00000,0.00000,0.0,0.979008,0.00000,0.00000,0.00000,0.0,0.0,0.0
3,2014-04-10,0.00000,0.00000,0.00000,0.0,0.545759,0.00000,0.00000,0.00000,0.0,0.0,0.0
4,2014-04-11,310.37614,96.87589,277.27826,0.0,1.215987,33.09788,10.47992,33.07195,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
973,2016-09-13,345.90677,90.03433,345.90677,0.0,0.999251,0.00000,0.00000,13.97408,0.0,0.0,0.0
974,2016-09-14,345.90677,90.03433,345.90677,0.0,1.049490,0.00000,0.00000,14.06316,0.0,0.0,0.0
975,2016-09-15,345.90677,90.03433,345.90677,0.0,0.974846,0.00000,0.00000,14.17445,0.0,0.0,0.0
976,2016-09-16,345.90677,90.03433,345.90677,0.0,0.968742,0.00000,0.00000,14.23277,0.0,0.0,0.0
977,2016-09-17,345.90677,90.03433,345.90677,0.0,0.990500,0.00000,0.00000,14.26085,0.0,0.0,0.0

In [15]:
fluid_list = ['OIL', 'GAS']

for fluid in fluid_list:
    fluid_df = df[['DATEPRD', f'BORE_{fluid}_VOL']].groupby('DATEPRD').sum()
    fluid_df.to_csv(f'../datasets/consolidated_data/{fluid.lower()}_data.csv')